import puppeteer from 'puppeteer';
import PptxGenJS from 'pptxgenjs';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const generatePresentation = async () => {
    console.log('Starting Presentation Generation...');

    // Setup Directories
    const screenshotDir = path.join(__dirname, 'screenshots');
    if (!fs.existsSync(screenshotDir)) fs.mkdirSync(screenshotDir);

    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';

    // Title Slide
    let slide = pptx.addSlide();
    slide.addText('Enquiry Management System', { x: 1, y: 1.5, w: '80%', fontSize: 36, bold: true, align: 'center', color: '363636' });
    slide.addText('User Operation Manual', { x: 1, y: 2.5, w: '80%', fontSize: 24, align: 'center', color: '6e6e6e' });
    slide.addText('Generated by AntiGravity', { x: 1, y: 5, w: '80%', fontSize: 14, align: 'center', color: 'aaaaaa' });

    // Launch Browser
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        defaultViewport: { width: 1366, height: 768 }
    });
    const page = await browser.newPage();

    try {
        // LOGIN
        console.log('Navigating to Login...');
        await page.goto('http://localhost:5173', { waitUntil: 'load', timeout: 60000 });
        await page.waitForSelector('input[type="email"]', { timeout: 10000 });

        // Step 1: Email
        console.log('Entering Email...');
        await page.type('input[type="email"]', 'bmselveng1@almoayyedcg.com');

        console.log('Clicking Next...');
        await page.click('button[type="submit"]');

        // Wait for Password Step
        console.log('Waiting for Password input...');
        await page.waitForSelector('input[type="password"]', { timeout: 10000 });

        // Step 2: Password
        console.log('Entering Password...');
        await page.type('input[type="password"]', '123456');

        // Capture Login
        const loginPath = path.join(screenshotDir, '1_login.png');
        await page.screenshot({ path: loginPath });

        slide = pptx.addSlide();
        slide.addText('1. Login Screen', { x: 0.5, y: 0.5, fontSize: 18, bold: true });
        slide.addImage({ path: loginPath, x: 0.5, y: 1.0, w: 9, h: 5 });
        slide.addText('Enter your Email ID and Password to access the system.', { x: 0.5, y: 6.2, fontSize: 12 });

        console.log('Clicking Sign In...');
        await page.click('button[type="submit"]');

        console.log('Waiting for Dashboard...');
        await page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 30000 }).catch(e => console.log('Nav timeout, checking specific element'));

        // Force wait for something characteristic of dashboard, e.g., 'Dashboard' text or specific class
        // Assuming dashboard has 'Dashboard' text visible
        // await page.waitForSelector('text/Dashboard', {timeout: 5000}).catch(e=>console.log('Dashboard text not found strictly'));

        // DASHBOARD
        console.log('Capturing Dashboard...');
        const dashboardPath = path.join(screenshotDir, '2_dashboard.png');
        await page.screenshot({ path: dashboardPath });

        slide = pptx.addSlide();
        slide.addText('2. Dashboard', { x: 0.5, y: 0.5, fontSize: 18, bold: true });
        slide.addImage({ path: dashboardPath, x: 0.5, y: 1.0, w: 9, h: 5 });
        slide.addText('The dashboard provides an overview of open enquiries, pending quotes, and recent activity.', { x: 0.5, y: 6.2, fontSize: 12 });

        // ENQUIRY
        console.log('Navigating to Enquiry...');
        try {
            const [enquiryBtn] = await page.$x("//button[contains(., 'Enquiry')]");
            if (enquiryBtn) await enquiryBtn.click();
            await new Promise(r => setTimeout(r, 2000));
        } catch (e) { console.error('Nav error Enquiry', e); }

        const enquiryPath = path.join(screenshotDir, '3_enquiry.png');
        await page.screenshot({ path: enquiryPath });

        slide = pptx.addSlide();
        slide.addText('3. Enquiry Module', { x: 0.5, y: 0.5, fontSize: 18, bold: true });
        slide.addImage({ path: enquiryPath, x: 0.5, y: 1.0, w: 9, h: 5 });
        slide.addText('Manage all incoming enquiries. Use "New Enquiry" to add, or Search to find existing records.', { x: 0.5, y: 6.2, fontSize: 12 });

        // PRICING (Simulate Navigation)
        console.log('Navigating to Pricing...');
        try {
            const [pricingBtn] = await page.$x("//button[contains(., 'Pricing')]");
            if (pricingBtn) await pricingBtn.click();
            await new Promise(r => setTimeout(r, 2000));
        } catch (e) { console.error('Nav error Pricing', e); }

        const pricingPath = path.join(screenshotDir, '4_pricing.png');
        await page.screenshot({ path: pricingPath });

        slide = pptx.addSlide();
        slide.addText('4. Pricing Module', { x: 0.5, y: 0.5, fontSize: 18, bold: true });
        slide.addImage({ path: pricingPath, x: 0.5, y: 1.0, w: 9, h: 5 });
        slide.addText('Perform detailed cost estimations for labor, materials, and overheads.', { x: 0.5, y: 6.2, fontSize: 12 });

        // QUOTE (Simulate Navigation)
        console.log('Navigating to Quote...');
        try {
            const [quoteBtn] = await page.$x("//button[contains(., 'Quote')]");
            if (quoteBtn) await quoteBtn.click();
            await new Promise(r => setTimeout(r, 2000));
        } catch (e) { console.error('Nav error Quote', e); }

        const quotePath = path.join(screenshotDir, '5_quote.png');
        await page.screenshot({ path: quotePath });

        slide = pptx.addSlide();
        slide.addText('5. Quote Generation', { x: 0.5, y: 0.5, fontSize: 18, bold: true });
        slide.addImage({ path: quotePath, x: 0.5, y: 1.0, w: 9, h: 5 });
        slide.addText('Generate professional quotations for customers based on approved pricing.', { x: 0.5, y: 6.2, fontSize: 12 });

        // Save PPT
        const outputPath = path.join(__dirname, 'EMS_Training_Presentation.pptx');
        await pptx.writeFile({ fileName: outputPath });
        console.log(`Presentation saved to: ${outputPath}`);

    } catch (err) {
        console.error('Error in generation:', err);
        // Try to snap error state
        await page.screenshot({ path: path.join(screenshotDir, 'error_state.png') });
    } finally {
        await browser.close();
        process.exit(0);
    }
};

generatePresentation();
